import { Component, OnInit } from "@angular/core";
import { FormControl } from "@angular/forms";
import { startWith, map } from "rxjs/operators";
import { Observable } from "rxjs";

interface Food {
  name: string;
  value: number;
}

@Component({
  selector: "app-food-ph-indicator",
  templateUrl: "./food-ph-indicator.component.html",
  styleUrls: ["./food-ph-indicator.component.scss"]
})
export class FoodPhIndicatorComponent implements OnInit {
  foodOptions: Food[];
  filteredfoodOptions$;
  selectedFood = { name: "Default", value: 8 };
  foodInputCtrl = new FormControl("");
  bridgeVariable = this.selectedFood;
  about = false;

  constructor() {}

  ngOnInit() {
    this.foodOptions = [
      { name: "Bacon", value: 3 },
      { name: "Sausages", value: 3 },
      { name: "Processed Cheeses", value: 3 },
      { name: "Colas", value: 3 },
      { name: "Pudding", value: 3 },
      { name: "French Fries & most other fried foods", value: 3 },
      { name: "Yeast", value: 3 },
      { name: "Canned Tuna", value: 4 },
      { name: "Lobster", value: 4 },
      { name: "Ice Cream", value: 4 },
      { name: "Nuts:Most Roasted Nuts", value: 4 },
      { name: "Hazelnuts", value: 4 },
      { name: "Carbonated Soft Drinks(Except Colas)", value: 4 },
      { name: "Sugar added Grapefruit & Orange Juice", value: 4 },
      { name: "Cottonseed & Palm oil", value: 4 },
      { name: "Most Legumes", value: 4 },
      { name: "Snow Peas", value: 4 },
      { name: "Tomato Sauce", value: 4 },
      { name: "Veal", value: 4 },
      { name: "Buttermilk", value: 4 },
      { name: "Cream Cheese", value: 4 },
      { name: "Granola", value: 4 },
      { name: "White Bread", value: 4 },
      { name: "Flour Tortilas", value: 4 },
      { name: "Artificial Sweeteners", value: 4 },
      { name: "White Vinegar", value: 4 },
      { name: "Beef & Pork", value: 5 },
      { name: "Mussels", value: 5 },
      { name: "Squid & other Mollusks", value: 5 },
      { name: "Goat Cheese", value: 5 },
      { name: "White Pasta", value: 5 },
      { name: "Most Beers", value: 5 },
      { name: "Black Teas", value: 5 },
      { name: "Hard Liquor", value: 5 },
      { name: "Most Coffee", value: 5 },
      { name: "Sugar added Fruit juices", value: 5 },
      { name: "Jams & Jellies", value: 5 },
      { name: "Pastries from White flour & Sugar", value: 5 },
      { name: "White Sugar", value: 5 },
      { name: "Most Microwave foods", value: 5 },
      { name: "Unsweetened Cocoa", value: 5 },
      { name: "Most Frozen & Canned Vegetables", value: 5 },
      { name: "Cooked Swiss Chard", value: 5 },
      { name: "Navy Beans", value: 5 },
      { name: "Most Wild Game", value: 5 },
      { name: "Cottage Cheese", value: 5 },
      { name: "Barley", value: 5 },
      { name: "Oat Bran", value: 5 },
      { name: "Rice Cakes", value: 5 },
      { name: "Most Wine", value: 5 },
      { name: "Powdered or Liquid Stevia", value: 5 },
      { name: "Balsamic Vinegar", value: 5 },
      { name: "Cigarettes", value: 5 },
      { name: "Iodized Table Salt", value: 5 },
      { name: "Pomegranate", value: 6 },
      { name: "Garbanzo Beans", value: 6 },
      { name: "Lima Beans", value: 6 },
      { name: "Chicken, Turkey", value: 6 },
      { name: "Duck & Goose", value: 6 },
      { name: "Verison & Elk", value: 6 },
      { name: "Processed Cereals", value: 6 },
      { name: "Rice White", value: 6 },
      { name: "Semolina", value: 6 },
      { name: "Wheat Bran", value: 6 },
      { name: "White & White Flour", value: 6 },
      { name: "Brazil Nuts & Walnuts", value: 6 },
      { name: "Pecans", value: 6 },
      { name: "Sesame", value: 6 },
      { name: "Safflower & Almond Oil", value: 6 },
      { name: "Reverse Osmosis Filtered Water", value: 6 },
      { name: "Most Bottle Waters & Sports Drinks", value: 6 },
      { name: "Brown Sugar", value: 6 },
      { name: "Chocolate", value: 6 },
      { name: "Custard with White Sugar", value: 6 },
      { name: "Sweetened Yogurt", value: 6 },
      { name: "Tapioca", value: 6 },
      { name: "Ketchup", value: 6 },
      { name: "Jar Mayonnaise", value: 6 },
      { name: "Mustard", value: 6 },
      { name: "Vanilla", value: 6 },
      { name: "Most Pharmaceutical Drugs", value: 6 },
      { name: "Dates, Figs & Other Dried Fruits", value: 6 },
      { name: "Cooked Cranberries", value: 6 },
      { name: "Prunes", value: 6 },
      { name: "Black-Eyed Peas", value: 6 },
      { name: "Peeled Potatoes", value: 6 },
      { name: "Most Pickles", value: 6 },
      { name: "Cooked Zucchini", value: 6 },
      { name: "Salmon, Tuna & Most Other Fish", value: 6 },
      { name: "Oysters & Most Shellfish", value: 6 },
      { name: "Plain Yogurt", value: 6 },
      { name: "Corn Bread & Tortillas", value: 6 },
      { name: "Cream of Wheat", value: 6 },
      { name: "Most Whole Grain Breads", value: 6 },
      { name: "Popcorn with Salt & Butter", value: 6 },
      { name: "Rye. Wheat & Wheat Germ", value: 6 },
      { name: "Pistachios & Pine Nuts", value: 6 },
      { name: "Kona Coffee", value: 6 },
      { name: "Soy, Rice & Almond Milk", value: 6 },
      { name: "Salted Butter", value: 6 },
      { name: "Pumpkin & Grape Seed Oil", value: 6 },
      { name: "Processed Maply Syrup", value: 6 },
      { name: "Sulpuerd Molasses", value: 6 },
      { name: "Gelatin", value: 6 },
      { name: "Hummus", value: 6 },
      { name: "Green Bananas", value: 7 },
      { name: "Plums", value: 7 },
      { name: "Cooked Green Peas", value: 7 },
      { name: "Horseradish", value: 7 },
      { name: "Kidney and Pinto Beans", value: 7 },
      { name: "Pickled Olives", value: 7 },
      { name: "Cooked Spinach", value: 7 },
      { name: "Cooked Whole Eggs & Egg Whites", value: 7 },
      { name: "Liver & Other Organ Meats", value: 7 },
      { name: "PRocessed Cow & Goat Milk", value: 7 },
      { name: "Processed Dairy Products", value: 7 },
      { name: "Most Cheeses", value: 7 },
      { name: "Oats", value: 7 },
      { name: "Buckwheat", value: 7 },
      { name: "Corn & Rice Breads", value: 7 },
      { name: "Commeal", value: 7 },
      { name: "Buttered Popcorn with no Salt", value: 7 },
      { name: "Sprout Breads", value: 7 },
      { name: "Sunflower Seeds", value: 7 },
      { name: "Wheat, Rye & Rice Crackers", value: 7 },
      { name: "Whole Grain", value: 7 },
      { name: "Rice Vinegar", value: 7 },
      { name: "Soy Cheese", value: 7 },
      { name: "Soy Sauce", value: 7 },
      { name: "Carob", value: 7 },
      { name: "Fructose", value: 7 },
      { name: "Pastries from Honey & Whole Grain", value: 7 },
      { name: "Egg Yolks Cooked Soft", value: 7 },
      { name: "Unsalted Butter & Margarine", value: 7 },
      { name: "Raw Cow & Goat Milk", value: 7 },
      { name: "Raw Cow & Goat Whey", value: 7 },
      { name: "Raw Cream", value: 7 },
      { name: "Brown & Basmati Rice", value: 7 },
      { name: "Municipal Tap Water", value: 7 },
      { name: "Carola, Corn & Sunflower Oil", value: 7 },
      { name: "Barley Malt Syrup", value: 7 },
      { name: "Raw Honey", value: 7 },
      { name: "Blueberries", value: 8 },
      { name: "Fresh Coconut", value: 8 },
      { name: "Raw Cranberries", value: 8 },
      { name: "Fresh Guava & Sapole", value: 8 },
      { name: "Strawberries", value: 8 },
      { name: "Bamboo Shoots", value: 8 },
      { name: "Beets without Greens", value: 8 },
      { name: "Chives", value: 8 },
      { name: "Cooked Brussel Sprouts & Broccoli", value: 8 },
      { name: "Cooked Squash & Eggplant", value: 8 },
      { name: "Corn Fresh", value: 8 },
      { name: "Cooked Kale", value: 8 },
      { name: "Cooked Soy Beans", value: 8 },
      { name: "Okra", value: 8 },
      { name: "Potatoes with Skins", value: 8 },
      { name: "Radishes / Tofu", value: 8 },
      { name: "Flax seeds", value: 8 },
      { name: "Miletm Spelt & Quinoa", value: 8 },
      { name: "Chestnuts", value: 8 },
      { name: "Unprocessed Apple Cider", value: 8 },
      { name: "Grain Coffee Substitutes", value: 8 },
      { name: "Flax, Avocado & Primrose Oil", value: 8 },
      { name: "Raw Maple Syrup", value: 8 },
      { name: "Homemade Mayonnaise", value: 8 },
      { name: "Sea Salt", value: 8 },
      { name: "Tamari Sauce", value: 8 },
      { name: "Apples", value: 8 },
      { name: "Currants", value: 8 },
      { name: "Gooseberries", value: 8 },
      { name: "Ripe Bananas", value: 8 },
      { name: "Fresh Oranges", value: 8 },
      { name: "Fresh Peaches", value: 8 },
      { name: "Bell Pepper", value: 8 },
      { name: "Cauliflower", value: 8 },
      { name: "Raw Green Cabbage", value: 8 },
      { name: "Fresh Musrooms", value: 8 },
      { name: "Jicarna & Arrowroot", value: 8 },
      { name: "Fresh Pumpkin", value: 8 },
      { name: "Fresh Ripe Olives", value: 8 },
      { name: "Fresh Tomato", value: 8 },
      { name: "Turnips, Parsnip & Kohlrabi", value: 8 },
      { name: "Turnip Greens", value: 8 },
      { name: "Wilde Rice", value: 8 },
      { name: "Sesame Seeds", value: 8 },
      { name: "Almonds", value: 8 },
      { name: "Natural Unsweetened Fruit Juices", value: 8 },
      { name: "Sake", value: 8 },
      { name: "Fish Oil", value: 8 },
      { name: "Unsulpured Molasses", value: 8 },
      { name: "Most Fresh Herbs & Spices", value: 8 },
      { name: "Miso Soup", value: 8 },
      { name: "Vegetable Sea Salt", value: 8 },
      { name: "Apple Cider", value: 8 },
      { name: "Vinegar", value: 8 },
      { name: "Blackberries", value: 9 },
      { name: "Cantaloupe", value: 9 },
      { name: "Honeydew & Most Melons", value: 9 },
      { name: "Fresh Apricots", value: 9 },
      { name: "Fresh Dates & Figs", value: 9 },
      { name: "Grapefruit", value: 9 },
      { name: "Grapes", value: 9 },
      { name: "Kiwi", value: 9 },
      { name: "Nedarine", value: 9 },
      { name: "Fresh Pears", value: 9 },
      { name: "Papaya & Passion Fruit", value: 9 },
      { name: "Raisins", value: 9 },
      { name: "Alfalfa & Other Sprouted Grains", value: 9 },
      { name: "Carrots", value: 9 },
      { name: "Fresh Garlic & Ginseng", value: 9 },
      { name: "Green Beans", value: 9 },
      { name: "Kudzu Root", value: 9 },
      { name: "Most Lettuces", value: 9 },
      { name: "Onions & Leaks", value: 9 },
      { name: "Rufabagas", value: 9 },
      { name: "Taro Root", value: 9 },
      { name: "Fresh Sweet Peas", value: 9 },
      { name: "Ginger & Mu Tea", value: 9 },
      { name: "Cayenne", value: 9 },
      { name: "Cinnamon", value: 9 },
      { name: "Loganberries", value: 9 },
      { name: "Persimmons", value: 9 },
      { name: "Fresh Mangoes & Pineapple", value: 9 },
      { name: "Fresh Raspberries", value: 9 },
      { name: "Tangerines", value: 9 },
      { name: "Umeboshi Plums", value: 9 },
      { name: "Artichokes", value: 9 },
      { name: "Beets with Green", value: 9 },
      { name: "Raw Celery", value: 9 },
      { name: "Raw Cucumber", value: 9 },
      { name: "Endive", value: 9 },
      { name: "Raw Eggplant", value: 9 },
      { name: "Raw Red Cabbage", value: 9 },
      { name: "Sweet Potatoes & Yams", value: 9 },
      { name: "Dried Soy Beans", value: 9 },
      { name: "Unroasted Dried Pumpkin Seeds", value: 9 },
      { name: "Sea Vegetables", value: 9 },
      { name: "Watercress", value: 9 },
      { name: "Raw Zucchini", value: 9 },
      { name: "Green & Herbal Teas", value: 9 },
      { name: "Cilantro", value: 9 },
      { name: "Parsley", value: 9 },
      { name: "Stevia Plant", value: 9 },
      { name: "Kelp, Karengo & Other Seaweed", value: 9 },
      { name: "Watermelon", value: 10 },
      { name: "Raw Broccoli", value: 10 },
      { name: "Straw Wheat, Lemon & Other Green Grasses", value: 10 },
      { name: "Potato Skins Only", value: 10 },
      { name: "Raw Kale", value: 10 },
      { name: "Raw Mustard Greens", value: 10 },
      { name: "Fresh Raw Vegetable Juices", value: 10 },
      { name: "Blended Green Grasses Drinks", value: 10 },
      { name: "Fresh Lemon", value: 10 },
      { name: "Raw Brussel", value: 10 },
      { name: "Sprouts", value: 10 },
      { name: "Raw Swiss Chard", value: 10 },
      { name: "Kimchi & other Fermented Vegetables", value: 10 },
      { name: "Raw Spinach", value: 10 },
      { name: "Baking Soda", value: 10 }
    ].sort((a, b) => (a.name < b.name ? -1 : 1));
    
    this.filteredfoodOptions$ = this.foodInputCtrl.valueChanges.pipe(
      startWith(""),
      map((value) => (typeof value === "string" ? value : value.name)),
      map((name) =>
        name ? this.filterFoodOptions(name) : this.foodOptions.slice()
      )
    );
  }

  filterFoodOptions(foodName: string) {
    foodName = foodName?.toLowerCase();
    return this.foodOptions.filter((food) =>
      food.name.toLowerCase().includes(foodName)
    );
  }

  getSelectedFoodName(food: Food) {
    return food.name || "";
  }

  setSelectedFoodName(selectedFood: any) {
    this.selectedFood = selectedFood;
  }

  updateBridgeVariable() {
    this.bridgeVariable = this.selectedFood;
  }
}
